name: Nightly Refund Prediction

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 1 AM UTC

jobs:
  run_batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run batch prediction
        run: |
          mkdir -p results
          python batch_process.py

      - name: Upload predictions as artifact
        uses: actions/upload-artifact@v3
        with:
          name: refund_predictions
          path: results/*.csv
